### ISSUE TITLE
Train with one's own dataset

### ISSUE THREAD

**Issue by KevinWang676** [shivammehta25/Matcha-TTS#9]
Hi, I wonder how I can get the corresponding `.yaml` file (like `ljspeech.yaml`) when I'm working on my own dataset. In addition, have you tested the performance of Matcha-TTS for other languages like Chinese and is a relatively small dataset (like a 20-min dataset) okay? Thank you very much!

**Comment by shivammehta25** [comment]
Hello! Thank you for your interest in 🍵 Matcha-TTS.

---
> I wonder how I can get the corresponding .yaml file (like ljspeech.yaml) when I'm working on my own dataset.

For training with a different dataset, most parameters would be the same as `ljspeech.yaml`.  So you can essentially just copy that.Generally, I prefer resampling all my audio files to `22050` sampling rate instead of changing the audio parameters, as this solves the problem of finding a different vocoder. 
Then, You can generate mean and standard deviation for your dataset (for better standardisation) [using these steps I have added in README.md](https://github.com/shivammehta25/Matcha-TTS#train-with-your-own-dataset).
The major changes you would require:
In `YOUR_DATASET.yaml`
```yaml
name: NAME_YOUR_DATASET_ANYTHING_ARBITRARY
train_filelist_path: NEW_FILEPATHS
valid_filelist_path: NEW_FILEPATHS
data_statistics:
  mel_mean: <generate (better) or use lj_speech's value> 
  mel_std: <generate (better) or use lj_speech's value> 
cleaners: [?chinese_cleaner? ] # you will need to setup text normalisation rules as stated below
```

You can take a look at [vctk.yaml](https://github.com/shivammehta25/Matcha-TTS/blob/main/configs/data/vctk.yaml) and do something similar, use the defaults from `ljspeech.yaml` and override what you need for your specific dataset.

For phonemisation: (again, I have no experience in training with Chinese dataset but you can change the phonemizer language here, I think for mandarin it is `zh` with `espeak` backend and `cmn` with `espeak-ng` backend. 

https://github.com/shivammehta25/Matcha-TTS/blob/2cd057187b8002afd1916ee8499474be05b55104/matcha/text/cleaners.py#L28

---

> Have you tested the performance of Matcha-TTS for other languages like Chinese

I haven't tried it. However, I do not see any reason for it to perform poorly as long as the alignment problem is monotonic.

---

> Is a relatively small dataset (like a 20-min dataset) okay? 

Again, I haven't tested it but the Monotonic alignment is very useful for jointly learning to speak and train. Even with a small dataset (especially if it is a studio-recorded dataset of read speech). I feel It depends largely on the dataset quality and the possibility of aligning it monotonically.  However, fine-tuning should mostly work better than training from scratch in such scenarios, so, you can first train on a larger Chinese dataset and then fine-tune it for your specific one. 
[Something similar to what we did for OverFlow and it worked very well](https://shivammehta25.github.io/OverFlow/#fast-finetuning-to-different-voices).


Hope this answers your questions :)
